apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-container-deployment
  labels:
    app: auth-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-container
  template:
    metadata:
      labels:
        app: auth-container
    spec:
      containers:
      - name: auth-container
        image: dinedash-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        readinessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-container
spec:
  selector:
    app: auth-container
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
