apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-container-deployment
  labels:
    app: restaurant-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-container
  template:
    metadata:
      labels:
        app: restaurant-container
    spec:
      containers:
      - name: restaurant-container
        image: dinedash-restaurant:latest   
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-container
  labels:
    app: restaurant-container                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
spec:
  selector:
    app: restaurant-container
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
